language: php

php: 7.2

service: docker

before_install:
  # Install system dependencies.
  - sudo apt-get -y update
  - sudo apt-get -y install cgroup-bin curl

  # Download lando installer.
  - curl -fsSL -o /tmp/lando-latest.deb http://installer.kalabox.io/lando-latest-dev.deb

install:
  # Install lando.
  - sudo dpkg -i /tmp/lando-latest.deb

before_script:
  # Install project dependencies.
  - lando start

script:
  # Validate custom code.
  - lando composer validate:php
  - lando gulp validate:js
  - lando gulp validate:sass

  # Test custom code.
  - lando composer test:php

before_deploy:
  # Optimize the Composer autoloader before deployment.
  - lando composer install --optimize-autoloader --no-dev

deploy:
  # Production environment deployment.
  - provider: script
    skip_cleanup: true
    script: # add a deploy script
    on:
      all_branches: true
      tags: true
      condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+$

  # UAT environment deployment.
  - provider: script
    skip_cleanup: true
    script: # add a deploy script
    on:
      branch: uat

  # Development environment deployment.
  - provider: script
    skip_cleanup: true
    script: # add a deploy script
    on:
      branch: development
