language: php

php: 7.1

service: docker

before_install:
  # Install system dependencies.
  - sudo apt-get -y update
  - sudo apt-get -y install cgroup-bin curl

  # Download lando installer.
  - curl -fsSL -o /tmp/lando-latest.deb http://installer.kalabox.io/lando-latest-dev.deb

install:
  # Install lando.
  - sudo dpkg -i /tmp/lando-latest.deb

before_script:
  # Install project dependencies.
  - lando composer install
  - lando npm install

script:
  # Validate custom code.
  - lando composer validate:php
  - lando gulp validate:js
  - lando gulp validate:scss

  # Test custom code.
  - lando composer test:php
